version: '3'
services:
  mongodb1:
    image: mongo:6.0
    container_name: mongodb1
    command: mongod --replSet rs0 --bind_ip_all
    volumes:
      - mongodb1_data:/data/db
    ports:
      - 27027:27017
    networks:
      - mongodbcluster
  mongodb2:
    image: mongo:6.0
    container_name: mongodb2
    command: mongod --replSet rs0 --bind_ip_all
    volumes:
      - mongodb2_data:/data/db
    ports:
      - 27028:27017
    networks:
      - mongodbcluster
  mongodb3:
    image: mongo:6.0
    container_name: mongodb3
    command: mongod --replSet rs0 --bind_ip_all
    volumes:
      - mongodb3_data:/data/db
    ports:
      - 27029:27017
    networks:
      - mongodbcluster
volumes:
  mongodb1_data:
  mongodb2_data:
  mongodb3_data:
networks:
  mongodbcluster:
